/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.games.tubes;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int computer=0x7f020000;
        public static final int greenstar=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int pipe0=0x7f020003;
        public static final int pipe1=0x7f020004;
        public static final int pipe10=0x7f020005;
        public static final int pipe11=0x7f020006;
        public static final int pipe12=0x7f020007;
        public static final int pipe13=0x7f020008;
        public static final int pipe14=0x7f020009;
        public static final int pipe15=0x7f02000a;
        public static final int pipe2=0x7f02000b;
        public static final int pipe3=0x7f02000c;
        public static final int pipe4=0x7f02000d;
        public static final int pipe5=0x7f02000e;
        public static final int pipe6=0x7f02000f;
        public static final int pipe7=0x7f020010;
        public static final int pipe8=0x7f020011;
        public static final int pipe9=0x7f020012;
        public static final int pipeg0=0x7f020013;
        public static final int pipeg1=0x7f020014;
        public static final int pipeg10=0x7f020015;
        public static final int pipeg11=0x7f020016;
        public static final int pipeg12=0x7f020017;
        public static final int pipeg13=0x7f020018;
        public static final int pipeg14=0x7f020019;
        public static final int pipeg15=0x7f02001a;
        public static final int pipeg2=0x7f02001b;
        public static final int pipeg3=0x7f02001c;
        public static final int pipeg4=0x7f02001d;
        public static final int pipeg5=0x7f02001e;
        public static final int pipeg6=0x7f02001f;
        public static final int pipeg7=0x7f020020;
        public static final int pipeg8=0x7f020021;
        public static final int pipeg9=0x7f020022;
        public static final int redstar=0x7f020023;
        public static final int yellowstar=0x7f020024;
    }
    public static final class id {
        public static final int cancel=0x7f050008;
        public static final int grid=0x7f050003;
        public static final int height=0x7f050004;
        public static final int move_count=0x7f050002;
        public static final int ok=0x7f050007;
        public static final int puzzle_id=0x7f050001;
        public static final int puzzle_id_box=0x7f050006;
        public static final int score_row=0x7f050009;
        public static final int top_view=0x7f050000;
        public static final int width=0x7f050005;
    }
    public static final class layout {
        public static final int grid_layout=0x7f030000;
        public static final int main=0x7f030001;
        public static final int options_dialog_layout=0x7f030002;
        public static final int scores=0x7f030003;
        public static final int scores_row=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int grid_layout_text_text=0x7f040005;
        public static final int menu_string_options=0x7f040006;
        public static final int mode_gameover_prefix=0x7f040003;
        public static final int mode_gameover_suffix=0x7f040004;
        public static final int mode_pause=0x7f040002;
        public static final int mode_ready=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a SingleTileView.
         */
        public static final int[] SingleTileView = {
            
        };
        /** Attributes that can be used with a TileView.
         */
        public static final int[] TileView = {
            
        };
    };
}
